env:
  browser: true
  node: true
  meteor: true

plugins:
  - meteor

extends:
  - airbnb/base
  - plugin:meteor/recommended

rules:
  meteor/audit-argument-checks: 0 # Collection2 package verifies schemas

parserOptions:
  ecmaVersion: 6
  sourceType: "module"

globals:
  # Collections
  MarkingSchemes: true
  Marks: true
  Activities: true
  Units: true

  # Packages
  sAlert: true
  RouterAutoscroll: true
  jQuery: true
  ReactiveFromNow: true
  ReactiveTable: true
  Ground: true
  SimpleSchema: true
  Chartist: true
  BrowserPolicy: true
  FlowRouter: true
  BlazeLayout: true
